### ISSUE TITLE
Is this truly open source?

### ISSUE THREAD

**Issue by PDQ-Emily** [vinaypamnani/wmie2#3]
Hello, 

Is there a EULA with this product or is it open source? Can I distribute it without violating any agreements?

Thanks!
Emily

**Comment by MatthewKing** [comment]
The old website indicates that this project is released under the MS-PL license.

See: https://wmie.codeplex.com/license

**Comment by PDQ-Emily** [comment]
Do you know if it's still under that though? It doesn't show that license here.

**Comment by MatthewKing** [comment]
The code on GitHub is mostly unchanged from the version on CodePlex, so if you grab the code from CodePlex you can at least be sure that it's under MS-PL.

Otherwise you'll need to wait for a response from @vinaypamnani

**Comment by vinaypamnani** [comment]
Sorry I haven't been active here in a while, I just added a more permissive MIT license.
