### ISSUE TITLE
I can´t view Win32_PerfFormattedData_PerfOS_Memory  class in windows 2008 R2 and Windows server 2016

### ISSUE THREAD

**Issue by TuberViejuner** [vinaypamnani/wmie2#4]
I can´t view Win32_PerfFormattedData_PerfOS_Memory  class in windows 2008 R2 and Windows server 2016 but this class is visible on powershell.

**Comment by vinaypamnani** [comment]
Sorry for the (very) late response. By default, the Win32_Perf classes are hidden (as they're generally unused in my experience), but you can see them by checking the "Include Perf Classes" checkbox.
