### ISSUE TITLE
win7 -Namespace options does not output any data

### ISSUE THREAD

**Issue by hackersql** [vinaypamnani/wmie2#6]
```
$computer = $env:COMPUTERNAME
$namespace = "ROOT\CIMV2\ms_409"
$classname = "Win32_Process"

Write-Output "====================================="
Write-Output "COMPUTER : $computer "
Write-Output "CLASS    : $classname "
Write-Output "====================================="

Get-WmiObject -Class $classname -ComputerName $computer -Namespace $namespace |
    Select-Object * -ExcludeProperty PSComputerName, Scope, Path, Options, ClassPath, Properties, SystemProperties, Qualifiers, Site, Container |
    Format-List -Property [a-z]*
```
The existence of the -Namespace $namespace option does not output any data under win7. After removing it, it can output data.
在win7下存在-Namespace $namespace选项不会输出任何数据，去掉之后可以输出数据。
![image](https://user-images.githubusercontent.com/7439035/40895379-a6a6b7d6-67e1-11e8-95fd-d7a29a15ce22.png)

**Comment by vinaypamnani** [comment]
This is because the Win32_Process class within the root\cimv2\ms_409 namespace genuinely doesn't have any instances. When you remove the namespace, it defaults to root\cimv2, where Win32_Process has instances.
